#!/usr/bin/env python3
import pandas as pd

VIDEO_IDS = list(range(5))
OUTFILE = "/mnt/labNAS/Chris/mousesong/usv_calls/08_solosocial/02_20230919_um008_uf003_mf/02_social/process_audio/all_notes/concat_all_notes_corrected_features_temporal.csv"
CSV_FILE_PATHS = [
    f"/mnt/labNAS/Chris/mousesong/usv_calls/08_solosocial/02_20230919_um008_uf003_mf/02_social/process_audio/all_notes/000002{id_}/all_notes_corrected_features_temporal.csv"
    for id_ in VIDEO_IDS
]
print("Stacking...")
print(CSV_FILE_PATHS)
dfs = []
for hour_idx, csv_file in enumerate(CSV_FILE_PATHS):
    df = pd.read_csv(csv_file)
    df["start"] += hour_idx * 3600
    df["end"] += hour_idx * 3600
    dfs.append(df)
concatenated_df = pd.concat(dfs, axis=0)
concatenated_df.to_csv(OUTFILE, index=False)
print(f"Saved {OUTFILE}.")
